var annotated_dup =
[
    [ "gf_audio_decoder_t", "structgf__audio__decoder__t.html", "structgf__audio__decoder__t" ],
    [ "gf_audio_t", "structgf__audio__t.html", "structgf__audio__t" ],
    [ "gf_client_t", "structgf__client__t.html", "structgf__client__t" ],
    [ "gf_draw_driver_t", "structgf__draw__driver__t.html", null ],
    [ "gf_draw_driver_texture_t", "structgf__draw__driver__texture__t.html", null ],
    [ "gf_draw_platform_t", "structgf__draw__platform__t.html", null ],
    [ "gf_draw_t", "structgf__draw__t.html", "structgf__draw__t" ],
    [ "gf_engine_t", "structgf__engine__t.html", "structgf__engine__t" ],
    [ "gf_file_t", "structgf__file__t.html", "structgf__file__t" ],
    [ "gf_font_bbox_t", "structgf__font__bbox__t.html", "structgf__font__bbox__t" ],
    [ "gf_font_cache_t", "structgf__font__cache__t.html", "structgf__font__cache__t" ],
    [ "gf_font_glyph_t", "structgf__font__glyph__t.html", "structgf__font__glyph__t" ],
    [ "gf_font_store_t", "structgf__font__store__t.html", "structgf__font__store__t" ],
    [ "gf_font_t", "structgf__font__t.html", "structgf__font__t" ],
    [ "gf_graphic_color_t", "structgf__graphic__color__t.html", "structgf__graphic__color__t" ],
    [ "gf_gui_call_t", "structgf__gui__call__t.html", "structgf__gui__call__t" ],
    [ "gf_gui_component_t", "structgf__gui__component__t.html", "structgf__gui__component__t" ],
    [ "gf_gui_t", "structgf__gui__t.html", "structgf__gui__t" ],
    [ "gf_input_t", "structgf__input__t.html", "structgf__input__t" ],
    [ "gf_lua_t", "structgf__lua__t.html", "structgf__lua__t" ],
    [ "gf_mesh_t", "structgf__mesh__t.html", "structgf__mesh__t" ],
    [ "gf_mesh_triangle_t", "structgf__mesh__triangle__t.html", "structgf__mesh__triangle__t" ],
    [ "gf_model_t", "structgf__model__t.html", "structgf__model__t" ],
    [ "gf_physics_t", "structgf__physics__t.html", "structgf__physics__t" ],
    [ "gf_prop_t", "structgf__prop__t.html", "structgf__prop__t" ],
    [ "gf_resource_entry_t", "structgf__resource__entry__t.html", "structgf__resource__entry__t" ],
    [ "gf_resource_t", "structgf__resource__t.html", "structgf__resource__t" ],
    [ "gf_server_t", "structgf__server__t.html", "structgf__server__t" ],
    [ "gf_sound_context_t", "structgf__sound__context__t.html", null ],
    [ "gf_sound_t", "structgf__sound__t.html", "structgf__sound__t" ],
    [ "gf_texture_t", "structgf__texture__t.html", "structgf__texture__t" ],
    [ "gf_thread_context_t", "structgf__thread__context__t.html", "structgf__thread__context__t" ],
    [ "gf_thread_t", "structgf__thread__t.html", null ],
    [ "gf_version_t", "structgf__version__t.html", "structgf__version__t" ]
];